### ISSUE TITLE
Query Builder: Alias predicates don't connect

### ISSUE THREAD

**Issue by mrwunderbar666** [opted-eu/meteor-dev#48]
Running a query where the predicate has aliases returns wrong results:

E.g., `country` and `countries` (Germany, Austria, Switzerland)

This query returns 1 result:
`dgraph.type=NewsSource&countries*connector=AND&countries=0x1c4ff112&countries=0x1c4ff147&_max_results=25`

This uses the alias and the `AND` connector is not working properly (returns 8 results)
`dgraph.type=NewsSource&country*connector=AND&country=0x1c4ff112&country=0x1c4ff147&_max_results=25`

Reported by @iwellaway

**Comment by mrwunderbar666** [comment]
required additional wrapping of filters connected with `AND` in `dgraph_types.py` + forwarding the connector to the alias filter builder in `query.py`

@iwellaway should now work as expected

**Comment by iwellaway** [comment]
@mrwunderbar666 

Hi Paul, 

I’m still getting some odd results from the api when using the connectors/

Here’s an example using text_types:

This is with no connector:
https://meteor.balluff.dev/api/query/count?text_types=0x5511dc3&text_types=0x5512a8f
= 26

This is with ‘or’:
https://meteor.balluff.dev/api/query/count?text_types=0x5511dc3&text_types=0x5512a8f&text_types*connector=or
= 430

This is with ‘and’
https://meteor.balluff.dev/api/query/count?text_types=0x5511dc3&text_types=0x5512a8f&text_types*connector=and
= 430

Is there anything wrong with my URL?
